---
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending

categories:
  - title: "🚨 Breaking changes"
    labels:
      - "breaking-change"
      - "major"
  - title: "✨ New features"
    labels:
      - "feature"
      - "minor"
  - title: "🐛 Bug fixes"
    labels:
      - "bugfix"
  - title: "🧰 Maintenance"
    collapse-after: 3
    labels:
      - "ci"
      - "chore"
  - title: "📚 Documentation"
    labels:
      - "documentation"
  - title: "⬆️ Dependency updates"
    collapse-after: 3
    labels:
      - "dependencies"

exclude-labels:
  - "skip-changelog"

version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
  minor:
    labels:
      - "minor"
      - "feature"
  patch:
    labels:
      - "bugfix"
      - "chore"
      - "ci"
      - "dependencies"
      - "documentation"
  default: patch

autolabeler:
  - label: "documentation"
    files:
      - "*.md"
    branch:
      - '/docs{0,1}\/.+/'
  - label: "bugfix"
    title:
      - "/fix: .+/i"
      - "/bug: .+/i"
    branch:
      - '/fix\/.+/'
      - '/bug\/.+/'
  - label: "feature"
    title:
      - "/feat: .+/i"
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
    body:
      - '/implements #\d+/i'
  - label: "breaking-change"
    title:
      - "/breaking change: .+/i"

template: |
  ## Changes

  $CHANGES
